version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laptop_backend
    restart: unless-stopped
    ports:
      - "8000:8000"  # Expose backend directly on port 8000
    volumes:
      - ./backend:/app
      - backend_static:/app/static_collected
      - backend_media:/app/media
    environment:
      - DEBUG=False
      - SECRET_KEY=${DJANGO_SECRET_KEY:-default_secret_key_for_dev}
      - ALLOWED_HOSTS=localhost,127.0.0.1,*
      - DATABASE_URL=sqlite:////app/db.sqlite3
    networks:
      - laptop_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: laptop_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"  # Expose frontend directly on port 3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    networks:
      - laptop_network
    depends_on:
      - backend

networks:
  laptop_network:
    name: laptop_network
    driver: bridge

volumes:
  backend_static:
  backend_media:
