
services:
  traefik:
    image: traefik:v2.10
    container_name: laptop_traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "0.0.0.0:80:80"  # Explicitly bind to all interfaces
      - "0.0.0.0:443:443"  # Explicitly bind to all interfaces
      - "0.0.0.0:8080:8080"  # Make dashboard accessible from local network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/config:/etc/traefik/config:ro
      - ./traefik/acme.json:/acme.json:rw
    networks:
      - laptop_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`traefik.eshop.qamdm.xyz`) || PathPrefix(`/api`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$ruca84Hq$$mbjdMZpxBhuM4MMRn4dI30"  # admin:password
      - "traefik.http.routers.traefik.middlewares=traefik-auth"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laptop_backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - backend_static:/app/static_collected
      - backend_media:/app/media
    environment:
      - DEBUG=False
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=localhost,127.0.0.1,192.168.1.69,eshop.qamdm.xyz
      - CSRF_TRUSTED_ORIGINS=https://eshop.qamdm.xyz
      - DATABASE_URL=sqlite:////app/db.sqlite3
    networks:
      - laptop_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`eshop.qamdm.xyz`) && (PathPrefix(`/api`) || PathPrefix(`/admin`) || PathPrefix(`/static`) || PathPrefix(`/media`))"
      - "traefik.http.routers.backend.entrypoints=web"
      # Removing TLS config as Cloudflare tunnel handles encryption
      - "traefik.http.routers.backend.priority=2"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: laptop_frontend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=https://eshop.qamdm.xyz/api/v1
    networks:
      - laptop_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`eshop.qamdm.xyz`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      # Removing TLS config as Cloudflare tunnel handles encryption
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      
  # Cloudflared tunnel is running on the Proxmox host
  # No need for a cloudflared service in docker-compose

networks:
  laptop_network:
    name: laptop_network
    driver: bridge

volumes:
  backend_static:
  backend_media:
