http:
  routers:
    test:
      rule: "Host(`eshop.qamdm.xyz`) && Path(`/test`)"
      service: "test"
      entryPoints:
        - "web"
  
  services:
    test:
      loadBalancer:
        servers:
          - url: "http://laptop_frontend:3000"
        passHostHeader: true
